name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
    USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ env.USERNAME }}
          password: ${{ env.PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: abrezdn1/girlhacks24-be:latest # Uses the branch name for tagging
          platforms: linux/amd64,linux/arm64 # Multi-platform support
          cache-from: type=registry,ref=tabrezdn1/girlhacks24-be:cache
          cache-to: type=inline,mode=max
